### ISSUE TITLE
Biodiesel production testing, per request.

### ISSUE THREAD

**Issue by Doomgull** [breakinblocks/nutsandboltstorqued#108]
Assuming zero pre-existing stockpile of raw materials, a 15x15 (max size octadic) EIO farm with only AA earthworms for "acceleration" can produce 6400mb of diesel fuel in 10 minutes using wheat and potatoes, assuming sufficient light to grow constantly (lighting or perma-day). The potato growth slightly edges out wheat seed production over 10s of minutes.

This is no-where near close to maxing out even a single processing setup. Without accelerators or agricraft crops for melon abuse, this is the still the most effective crop selection setup. Hemp's higher seed oil rate is counteracted by it's slower growth rate, unless sufficient accelerators are brought to bear to make both crop types an equal harvest speed.

However, assuming sufficient accelerators on the crops to keep a single squeezer and single fermenter supplied at full rate, a single refinery will produce 19000mb of diesel in 60 seconds. The refinery is the restriction in this configuration, with the ratio of Refineries to Squeezers/Fermenter pair at 3 Refineries per 2 of each Squeezer/Refinery.

Difference of 10 mb/s vs 315 mb/s biodiesel production from normal crop growth rate vs full refining rate.

**Comment by Doomgull** [comment]
And follow-up testing with Compression Dynamo:

Diesel Gen will turn out ~500k Rf for a bucket of diesel fuel at 4096 rf/t.
Compression dynamo will turn out ~3 million rf for a bucket of diesel fuel at 40 rf/t.

Doesn't seem to be a way at present to upgrade compression dynamos.

**Comment by Saereth** [comment]
compression dynamos can be upgraded now, rf values look solid, biodiesel should be a viable midgame power
