### ISSUE TITLE
Flukes crash logs

### ISSUE THREAD

**Issue by superfluke** [breakinblocks/nutsandboltstorqued#111]
Here's a nice collection of logs, 4 different crashes. Had the most problems when trying to switch dimensions.
1: https://paste.ee/p/TIvXh
2: https://paste.ee/p/vX5Sd
3: https://paste.ee/p/TlBEM
4: https://paste.ee/p/FTHfR

**Comment by Saereth** [comment]
These should all be resolved in the new update
