### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by ItsSchef** [breakinblocks/nutsandboltstorqued#115]
I wish I could remember the name, the item that you combine with a stone block to make stone dust.
5% of it's durability is used in the craft.  The item duplicates itself into 2 slightly used copies, as well as duplicates all stone in the bench at the time.  After 5% of its durability has been used, it is no longer usable in that recipe.  (It should have 19 more uses).

**Comment by Saereth** [comment]
This has been fixed in the new version
