### ISSUE TITLE
Dungeon infinite spawning

### ISSUE THREAD

**Issue by ItsSchef** [breakinblocks/nutsandboltstorqued#117]
Some dungeons spawn infinite mini zombies which cause the game to drop to below 1fps.  This is fixed by destroying the spawner (in creative) and restarting the server.  these zombies cannot be killed or moved.

**Comment by Saereth** [comment]
I have heard of this issue with roguelikes but I have never been able to reproduce it. I will keep an eye on this and open an new issue with them.

**Comment by Saereth** [comment]
This should be fixed now in today's update, think I found the culprit
