### ISSUE TITLE
HQM quests prerequisite backwards 

### ISSUE THREAD

**Issue by superfluke** [breakinblocks/nutsandboltstorqued#121]
The "Casting Assist!" quest requires the player to have completed the "Magic, Refined." quest, however the recipe progression requires the player to get psi dust before getting the essence refiner. I believe you meant to have the "Casting Assist!" be a prerequisite of the "Magic, Refined." quest.

**Comment by Saereth** [comment]
It would make more sense the otherway, I'll fix this in a future update

**Comment by superfluke** [comment]
Also noticed the "Raw Iridium" quest doesn't have any items set for detection so it cannot be completed.

**Comment by Saereth** [comment]
cool any more quest issues you find update this issue with if you dont mind, i'll be overhauling all the quests this weekend

**Comment by superfluke** [comment]
The induction power quest has trouble detecting the induction smelter

**Comment by Saereth** [comment]
all of these are fixed now
