### ISSUE TITLE
Starting a server

### ISSUE THREAD

**Issue by Peolr** [breakinblocks/nutsandboltstorqued#123]
I downloaded the latest Server files for Nuts and bolts torqued, and at first this "DiscordChat" mod made an error I fixed by renaming the conf to properties. Then it loads almost everything, but when it gets to woot, it gets stuck on this and uses 100% cpu forever:
"[10:31:42] [Server thread/INFO] [Woot]: LootTableManager: Load loot statistics from /home/mc/nad/woot/loot.json" It will sit there forever and do nothing but use all of the cpu. Is this normal?

**Comment by Saereth** [comment]
that is definitely not normal, hasnt been reported before either. Can you try temporarily removing the loot.json file and see if your server continues to boot? Let me know.

**Comment by Peolr** [comment]
I did do that, I re-named the woot folder to wootb and it still said it was trying to load the file. Updating woot to the latest version also did nothing.

**Comment by Saereth** [comment]
updating woot changes ALOT of core functionality in woot I wouldnt recommend that currently, we'll be migrating to that in a week or so, need to review all the changes for progression altering things. 

Can you link me your lastest.log file

**Comment by Peolr** [comment]
Alright I'll do another fresh install and give you the log file when it's done!

**Comment by Peolr** [comment]
Here's fml-server-latest.log. It seemed to be the one it was writing to.
Turns out the file was 2.5 MB, so here's the end of the paste:
https://pastebin.com/reShNSST
or the whole one on dropbox:
https://www.dropbox.com/s/awt2nkmfnbsddjj/fml-server-latest.log?dl=0

**Comment by Peolr** [comment]
Here's what the console looks like:
http://i.imgur.com/vQB95no.png

**Comment by Saereth** [comment]
Can you try removing the discord chat mod from your mods folder

**Comment by Peolr** [comment]
I also noticed a (possible?) memory leak when i forced closed the server after it froze.
Looks like removing Discord Chat from the mods folder did allow it to fully start.

**Comment by Saereth** [comment]
ok This is currently a known issue and it will be removed from the next update, previously it crashed most people instead of causing a hang though so I was concerned it was a separate issue, thanks for the followup
