### ISSUE TITLE
Iron Ore Dust in squeezer

### ISSUE THREAD

**Issue by tjsd** [breakinblocks/nutsandboltstorqued#125]
I have a problem with the first quest that requires you to use the squeezer for iron ore dust.

According to JEI it needs to be Goethite Iron ore, But I can not find that in aroma mining world or overworld. I can not use Siderite or Limonite in the squeezer to make the dust.

So I can not progress at all, could you please tell me if this is intended or a bug? It is not listed in the google docs sheet listing oregen either.

**Comment by Saereth** [comment]
Siderite, limonite, magnetite, hematite all smelt in a vanilla furnace to give varying amounts Geothite ore. http://imgur.com/a/D0MlN
