### ISSUE TITLE
Oredict issue

### ISSUE THREAD

**Issue by Waisse** [breakinblocks/nutsandboltstorqued#136]
Machine Chassis recipe specifically uses Mekanism steel ingot, it's not oredicted properly.

**Comment by Saereth** [comment]
This is actually intended to verify people have moved into mek processing before opening that tech path.

**Comment by Waisse** [comment]
There's a least 3 different to convert items with the same oredict, and one of them doesn't even need to have the desired item already.

**Comment by Saereth** [comment]
which one? lets get it out of there

**Comment by Saereth** [comment]
changed recipe
