### ISSUE TITLE
Books missing from enchiridon library

### ISSUE THREAD

**Issue by Xavion3** [breakinblocks/nutsandboltstorqued#137]
- Actually Additions Manual
- XNet Manual
- HQM book
- Woot manual
- RFTools Control
- Ore tiers guide (Rockhounding)
- Animus Compendium (Blood magic)
- Delving into Darkness (Blood magic)

**Comment by Saereth** [comment]
All of these are added next patch except for the ore tiers, doesnt wanna work right with enchriidion
