### ISSUE TITLE
Not Enough Wands inconsistency

### ISSUE THREAD

**Issue by Mofman1** [breakinblocks/nutsandboltstorqued#138]
Certain wands from Not Enough Wands require RF to operate, while others take experience. Specifically, the swapping and protection wand require experience. This makes the swapping wand rather questionable as a building tool.

**Comment by Saereth** [comment]
Protection wand now takes durability, Swapping wand now uses Rf and recipe a bit harder. Protection and acceleration wands should be the only 2 that use durability now.
