### ISSUE TITLE
General ore dict issues

### ISSUE THREAD

**Issue by Mofman1** [breakinblocks/nutsandboltstorqued#139]
The molecular assembler only accepts electrum from IE, and won't accept TE electrum.
Actually Additions medium and large crates don't have ore dict'ed electrum and steel respectively.

Do you way me filing these piddly little ore dict issues separately or should I save them up? lol

**Comment by Saereth** [comment]
keep them to one issue and I correct em all before the next update

**Comment by Saereth** [comment]
fixed next restart
