### ISSUE TITLE
Crafting obstructed by NBT from IC2, DE

### ISSUE THREAD

**Issue by marcus2518** [breakinblocks/nutsandboltstorqued#141]
Crafting of the quantum quarry block is obstructed by the NBT data on the IC2 components (lapotron, mining lasers)
Crafting of the Wyvern armor set is obstructed by the NBT data on the quantum armor pieces (26/27 durability)
Crafting of the Infinity Armor seems to require unupgraded, uncharged DE armor (clean NBT)

**Comment by Saereth** [comment]
infinity armor does require fresh DE armor, not much I can do about that atm since the withanytag option isnt currently working. All the rest of these issues are resolved next update
