### ISSUE TITLE
Suggestion; Adding recipe for Mekanism Creative gas tank

### ISSUE THREAD

**Issue by Jemsuper** [breakinblocks/nutsandboltstorqued#146]
Imagine the fun with the mekanism reactor. Also other more niche things are possible.

Also could be possible to make a seperate recipe for every filled creative tank, and it requires a filled ultimate tank for it craft that one (like how age of engineering did that)

**Comment by Saereth** [comment]
is there any scenario where this couldnt be achieved with the infinite fluid source and a rotary condenstrator?

**Comment by Jemsuper** [comment]
Its mostly that for example DT-fuel needs several steps of gas before it. So ye a liquid lithium and a heavy water fluid source (at the same time) would achieve this too. But it would also need several hundreds of neutron solar activators and other machines to achieve ultimate gas pipe speed.
