### ISSUE TITLE
1.6.4.7 - Mekanism Salt uncraftable

### ISSUE THREAD

**Issue by tworf** [breakinblocks/nutsandboltstorqued#150]
In 1.6.4.7 the recipe for Mekanism salt makes fresh water. 

The Sodium Chloride Compound recipe is not using the oreDict for salt also, it only uses the Mekanism salt.

**Comment by Saereth** [comment]
make a brine tower and use a chemical crystalizer, and yeah the sodium chloride recipe intentionally uses only mekanism salt as the other methods were much easier.
