### ISSUE TITLE
Metal dupe issue.

### ISSUE THREAD

**Issue by Grobes** [breakinblocks/nutsandboltstorqued#168]
When metal ingots are converted into two rods using the metal press or lathe, the rods can be put in a smeltery to end up with more metal than you started with.

The smeltery is balanced to three ingots to four rods, not 1 ingot to two rods.

Obviously anyone can use this to make infinte amounts of most metals.

**Comment by Saereth** [comment]
the best solution here is probably just disable the lathe I'd imagine, since it's not actually required for anything.  Will get something in the next update.

**Comment by Jemsuper** [comment]
The metal press does the same as the guy said. And you cant disable the metal press rod mold as that is used often

**Comment by Saereth** [comment]
that is not a great solution, requires manually redoing literally every single rod in tinkers.

**Comment by Jemsuper** [comment]
Meh thats kinda annoying ye. Though there are so many ways to do 2 ingots > 4 rods its really hard to stop. Some you can craft, some metal press, a lot multiple, some latch

**Comment by Doomgull** [comment]
#171 created to resolve issue, they'll only give 72 mb of molten liquid now instead of 108 mb. Accidentally crafting rods via crafting table will lose material, but accidentally using lathe/press to do it won't, now, since they'll properly remelt.

**Comment by Saereth** [comment]
fixed in next update, thanks doom
