### ISSUE TITLE
client crash when creating hqm party

### ISSUE THREAD

**Issue by XxShadowX** [breakinblocks/nutsandboltstorqued#169]
https://hastebin.com/omameguyap.sql

Hqm book is also empty when rejoining server, Quests are there in local world + other servers though.

**Comment by Saereth** [comment]
duplicate https://github.com/breakinblocks/nutsandboltstorqued/issues/114

**Comment by XxShadowX** [comment]
Is there no fix then? Lorddusk nor any contributors have replied to your original report a month ago.

**Comment by Doomgull** [comment]
It's an hqm issue, there's nothing that can be done on our end.
