### ISSUE TITLE
Avaritia Update Is Out!

### ISSUE THREAD

**Issue by ZzZDracoZzZ** [breakinblocks/nutsandboltstorqued#170]
Avaritia just updated and included all the 1.7 features, including those sexy renders! you should remove avaritia addons and update avaritia to the newest version =)

**Comment by Saereth** [comment]
Yeah I keep the pack very up to date in my dev environment and added it a few days ago, we're due for a released update soon. This is problematic though as the latest version of avaritia addons doesnt recognize the latest version of avaritia so it wont load. Meaning to upgrade we have to remove additions which will delete any avaritia addon blocks and items people have earned, was hoping for a work around but the Avaritia addons dev seems to have gone AWOL so we'll probably just bite the bullet and do the update this weekend. Sooner than later will be better to minimize impact.

**Comment by ZzZDracoZzZ** [comment]
@Saereth The new update seems big, i cant wait : P Does it rework the lack of special crafting interaction from other mods? Because right now the pack is exactly my cup of tea except for that and the lack of hqm progression, but you said the hqm was also getting a rework : P

**Comment by Doomgull** [comment]
Hqm needs to update and fix their bugs.

**Comment by Saereth** [comment]
yeah I have a bunch of new quests done but Im praying for an hqm update so everyone doesnt need to get reset again. If it doesnt happen soon I'll just have to release and force the reset :/
