### ISSUE TITLE
IC2 Coolant Recipe

### ISSUE THREAD

**Issue by Vsdgkk** [breakinblocks/nutsandboltstorqued#175]
Im not sure if this is actually an issue. But i cant seem to find out how to create ic2 coolant. I see its not disabled or anything, and the normal method doesnt work.

**Comment by Saereth** [comment]
normal method works fine, water or distilled water in a fluid canning machine on fluid enrich mode with macerated lapis

**Comment by Vsdgkk** [comment]
I mustve stuffed up somehow then. Loving the pack though, took a break from NH :)
