### ISSUE TITLE
Miniaturizarion fluid drop added recipe is not accesible anymore

### ISSUE THREAD

**Issue by Jemsuper** [breakinblocks/nutsandboltstorqued#176]
http://puu.sh/vJo8p/1044a5c192.jpg

**Comment by BlueAgent** [comment]
This seems to be specific to our server, [this line](https://github.com/breakinblocks/nutsandboltstorqued/blob/780058d6a5bc44c681cdae8ce17f8c671e48abc4/scripts/botania.zs#L59) was missing in the server configs.

Added the recipe back in again.
