### ISSUE TITLE
[Suggestion] Galacticraft

### ISSUE THREAD

**Issue by ZzZDracoZzZ** [breakinblocks/nutsandboltstorqued#177]
Have you considered adding galacticraft (once it releases) to the pack, replacing Advanced Rocketry? you could make custom ore generation in the different planets and using them as progression gates, similar to how GTNH did

also wheres new updaterino? : c

**Comment by Saereth** [comment]
I've considered this, or perhaps adding since they do work together. The mods I'm waiting for still havent udpated yet (none of them) so all I can say right now is soon ™

**Comment by ZzZDracoZzZ** [comment]
didnt you said earlier that you aint going to wait any longer and update the pack nevertheless?

**Comment by Doomgull** [comment]
He said he wasn't ping to wait for hqm dev to update anymore, but seeing that the other two mods that the update would be for also haven't updated, so there aren't bugfixes...

**Comment by Baughn** [comment]
I've had a lot of bad experiences with Galacticraft, to the point that I actively avoid packs that use it.

Just a dissenting opinion...

**Comment by Saereth** [comment]
I will revisit this in a future major packup, closing for now though
