### ISSUE TITLE
No recipe for compacting drawer

### ISSUE THREAD

**Issue by dyerseve** [breakinblocks/nutsandboltstorqued#194]
v1.6.4.7 server, in jei, no recipe and using the standard recipe doesn't produce anything. Not sure if intentional or a bug.

Edit: I see now it's in the general.zs as disabled. That's going to make storage difficult until we get AE2.

**Comment by Doomgull** [comment]
It's intentional, because it allows for an easy progression skip from the compacter.

**Comment by Saereth** [comment]
additionally since so many recipes are changed for blocks/removing etc it doesnt work as expected which lead to even more bug reports. Sooo as doomgul said we did remove it.
