### ISSUE TITLE
Woot xp shards require xp shards?

### ISSUE THREAD

**Issue by weedenbc** [breakinblocks/nutsandboltstorqued#205]
Trying to get xp shards, which AFAIK requires a woot mob factory with an xp upgrade. The current recipe for the upgrade requires a Luck of the Sea enchanted book. To make the book, you need an EnderIO enchanter, which requires...four xp shard to make the experience rod! Looks like that change was made in a recent update.

I guess you could probably randomly enchant books in a normal enchanting table and eventually get the right one, but that seems really grindy. 

Is there another option I'm missing?

**Comment by Doomgull** [comment]
Can't you just directly place a fishing rod into the normal enchanter to guarantee the enchantment, then yank the enchantment off using blood magic?

**Comment by Saereth** [comment]
yeah there are several ways to tackle this, and fishing/usign the AA fishing nets will passively gain you those books, yeah its more work now but this is not an oversight. enchanting fishing rod then removing the enchantment with bloodmagic is a pretty easy way to do it as well, you want to Animus ritual of unmaking.

**Comment by weedenbc** [comment]
Ok, I can see that, although that mechanic is not at all obvious, at least to us non-hardcore players :)

**Comment by Doomgull** [comment]
It's a vanilla mechanic. There's pretty liberal use of that through the whole pack (first nether portal, for instance).
