### ISSUE TITLE
Cannot find Child addon: 253171 Version 1.6.4.7

### ISSUE THREAD

**Issue by HappyPupppy** [breakinblocks/nutsandboltstorqued#206]
I get to about 130/180 mods installed and that message pops up everytime. I have tried 5 times to install the modpack and the error "cannot find child addon: 253171" comes up each time. I dont think its at the same mod each time, but i cannot be 100% sure about that. Any help would be great, this mod pack looks really fun and id love you play it.

**Comment by Doomgull** [comment]
What are you using to download the pack? If it's vazkii's CMPDL tool, try using portablejim's CurseDownloader instead and report back. It's not an issue with the pack, it's with the manifest and the tool pulling the mod from curse/twitch.

**Comment by HappyPupppy** [comment]
I had looked but i did not see the same issue. Its my bad, Im using the stupid Twitch Launcher. Curse was taken over and Twitch replaced the launcher. Ill go look at the other post.

**Comment by Doomgull** [comment]
May want to try using portablejim's tool. It works for windows, iirc.

It's a curse/twitch issue with the manifest, though. It happens off and on due to something on their end, unfortunately.

**Comment by HappyPupppy** [comment]
I will go ahead and try on the Twitch launcher again, if it doesnt ill for sure try Portablejim's tool.

**Comment by HappyPupppy** [comment]
Ok may be really easy to find, But im not finding portablejim's tool. Im a major noob i guess.

**Comment by Doomgull** [comment]
Googling "portablejim curse downloader" should pop it up.
