### ISSUE TITLE
[Suggestion] Swingthroughgrass (for combat)

### ISSUE THREAD

**Issue by Codystar44** [breakinblocks/nutsandboltstorqued#209]
Hey saereth im loving your pack but one of the most annoying issues is when you try to swing your sword at a zombie and it instead cuts the grass. Im sure youve experienced this before well Swingthroughgrass fixes that and i believe its almost essential for any pack... could you please add in the next update?

**Comment by Saereth** [comment]
I had some crashing issues with this mod last I tried but its been a bit I'll see if works now. Was a server side crasj
